### ISSUE TITLE
NoSuchFileException from UniversePackageCache.close

### ISSUE THREAD

**Issue by BenWhitehead** [dcos/cosmos#246]
```
java.nio.file.NoSuchFileException: /tmp/cosmos-it-6893504012476392066/L2Zvb2Jhcg==
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.8.0_72]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_72]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_72]
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244) ~[na:1.8.0_72]
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103) ~[na:1.8.0_72]
	at java.nio.file.Files.delete(Files.java:1126) ~[na:1.8.0_72]
	at com.mesosphere.cosmos.UniversePackageCache.close(UniversePackageCache.scala:103) ~[cosmos_2.11-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at com.mesosphere.cosmos.MultiRepository$$anonfun$repositories$1$$anonfun$apply$18.apply(MultiRepository.scala:94) ~[cosmos_2.11-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at com.mesosphere.cosmos.MultiRepository$$anonfun$repositories$1$$anonfun$apply$18.apply(MultiRepository.scala:93) ~[cosmos_2.11-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116) ~[scala-library-2.11.7.jar:na]
	at com.mesosphere.cosmos.MultiRepository$$anonfun$repositories$1.apply(MultiRepository.scala:93) ~[cosmos_2.11-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at com.mesosphere.cosmos.MultiRepository$$anonfun$repositories$1.apply(MultiRepository.scala:82) ~[cosmos_2.11-0.1.0-SNAPSHOT.jar:0.1.0-SNAPSHOT]
	at com.twitter.util.Future$$anonfun$map$1$$anonfun$apply$6.apply(Future.scala:950) ~[util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Try$.apply(Try.scala:13) ~[util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Future$.apply(Future.scala:97) ~[util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:950) ~[util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:949) ~[util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:112) ~[util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Promise$Transformer.k(Promise.scala:112) ~[util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:122) ~[util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:103) ~[util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Promise$$anon$1.run(Promise.scala:381) ~[util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:178) [util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:136) [util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:207) [util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:92) [util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Promise.runq(Promise.scala:350) [util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:721) [util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Promise.update(Promise.scala:694) [util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.util.Promise.setValue(Promise.scala:670) [util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:111) [util-core_2.11-6.30.0.jar:6.30.0]
	at com.twitter.finagle.netty3.transport.ChannelTransport.handleUpstream(ChannelTransport.scala:55) [finagle-core_2.11-6.31.0.jar:6.31.0]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.10.1.Final.jar:na]
	at com.twitter.finagle.netty3.channel.ChannelRequestStatsHandler.messageReceived(ChannelRequestStatsHandler.scala:35) [finagle-core_2.11-6.31.0.jar:6.31.0]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124) [netty-3.10.1.Final.jar:na]
	at com.twitter.finagle.http.codec.RespondToExpectContinue.messageReceived(RespondToExpectContinue.scala:30) [finagle-http_2.11-6.31.0.jar:6.31.0]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124) [netty-3.10.1.Final.jar:na]
	at com.twitter.finagle.http.codec.PayloadSizeHandler.messageReceived(PayloadSizeHandler.scala:23) [finagle-http_2.11-6.31.0.jar:6.31.0]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:82) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpServerCodec.handleUpstream(HttpServerCodec.java:56) [netty-3.10.1.Final.jar:na]
	at com.twitter.finagle.http.SafeHttpServerCodec.handleUpstream(Codec.scala:35) [finagle-http_2.11-6.31.0.jar:6.31.0]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.10.1.Final.jar:na]
	at com.twitter.finagle.netty3.channel.ChannelStatsHandler.messageReceived(ChannelStatsHandler.scala:78) [finagle-core_2.11-6.31.0.jar:6.31.0]
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.10.1.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.10.1.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
```

**Comment by cruhland** [comment]
No longer relevant now that `UniversePackageCache` is scheduled for deletion.
