### ISSUE TITLE
Errors when trying to build from source

### ISSUE THREAD

**Issue by bodymindarts** [dcos/cosmos#485]
Trying to build v0.2.0 via
`$ sbt one-jar`
results in:
```
(ommited)
[error] 2 not found
[error]   /Users/jcarter/.m2/repository/joda-time/joda-time/2.3/joda-time-2.3.jar
[error]   /Users/jcarter/.m2/repository/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar
java.lang.Exception: Encountered 2 errors (see above messages)
        at coursier.Tasks$$anonfun$updateTask$1.coursier$Tasks$$anonfun$$report$1(Tasks.scala:710)
        at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$49.apply(Tasks.scala:748)
        at coursier.Tasks$$anonfun$updateTask$1$$anonfun$apply$49.apply(Tasks.scala:748)
        at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:189)
        at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
        at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:741)
        at coursier.Tasks$$anonfun$updateTask$1.apply(Tasks.scala:517)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (cosmos-server/*:update) java.lang.Exception: Encountered 2 errors (see above messages)
[error] Total time: 16 s, completed Sep 3, 2016 7:07:44 PM
```
Would appreciate any help.

**Comment by BenWhitehead** [comment]
@bodymindarts Can you provide some details on your environment?

We're not seeing this error in any of our [CI](https://teamcity.mesosphere.io/project.html?projectId=DcosIo_Cosmos&tab=projectOverview) or dev machines (linux and mac).

**Comment by jsancio** [comment]
No Update in a while. Closing issue.
